#!/bin/sh
# DESCRIPTION: Example file to put in /etc/init.d to run daemon
#
# Copyright 2002-2009 by Wilson Snyder.  This program is free software;
# you can redistribute it and/or modify it under the terms of either the GNU
# Lesser General Public License Version 3 or the Perl Artistic License Version 2.0.
#
# chkconfig: 23456 99 10
# description: Slchoosed provides clump-wide scheduling services for Schedule::Load
# processname: slchoosed
#
### BEGIN INIT INFO
# Provides:          slchoosed
# Required-Start:    $syslog $remote_fs pidstatd
# Should-Start:      cron
# Required-Stop:
# Should-Stop:
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: slchoosed
# Description:       slchoosed
### END INIT INFO

state=$1
prog=/usr/local/bin/slchoosed

case $state in
  start)
	if [ $EUID != 0 ]; then
	    echo "Run as root, only root can do kill 0's"
	    exit 10
	fi
        if [ -f $prog ]; then
            echo starting $prog
	    su daemon -c $prog &
	else
	    echo Service broken, not found: $prog
	fi
	exit 0
        ;;
  stop)
        if test "x`pidof -o $$ -o $PPID -x slchoosed`" != x; then
                echo -n $"Stopping slchoosed: "
                kill `pidof -o $$ -o $PPID -x slchoosed`
                echo
        fi
	exit 0
        ;;
  restart|reload)
	$0 stop
	$0 start
	exit 0
	;;
  status)
        if test "x`pidof -o $$ -o $PPID -x slchoosed`" != x; then
		ps f -ww `pidof -o $$ -o $PPID -x slchoosed`
        fi
	exit 0
	;;
*)
	echo $"Usage: $0 {start|stop|restart|reload|status}"
	exit 1
esac
