#!/bin/sh
# DESCRIPTION: Example file to put in /etc/init.d to run daemon
#
# Copyright 2002-2006 by Wilson Snyder.  This program is free software;
# you can redistribute it and/or modify it under the terms of either the GNU
# General Public License or the Perl Artistic License.
#
# chkconfig: 23456 99 10
# description: Slreportd provides process reporting services for Schedule::Load
# processname: slreportd
#
### BEGIN INIT INFO
# Provides:          slreportd
# Required-Start:    $syslog $remote_fs $network
# Should-Start:      pidstatd
# Required-Stop:     $remote_fs $network
# Should-Stop:
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: slreportd
# Description:       slreportd
### END INIT INFO

state=$1
prog=/usr/local/bin/slreportd_site

case $state in
  start)
        if [ -f $prog ]; then
            echo starting $prog
	    #
	    rm -f /tmp/TTYDEVS
	    mkdir -p /usr/local/lib/rschedule
	    chmod a+rwx /usr/local/lib/rschedule
	    $prog &
	else
	    echo Service broken, not found: $prog
	fi
	exit 0
        ;;
  stop)
        if test "x`pidof -o $$ -o $PPID -x slreportd`" != x; then
                echo -n $"Stopping slreportd: "
                kill `pidof -o $$ -o $PPID -x slreportd`
                echo
        fi
	exit 0
        ;;
  restart|reload)
	$0 stop
	$0 start
	exit 0
	;;
  status)
        if test "x`pidof -o $$ -o $PPID -x slreportd`" != x; then
  	        ps f -ww `pidof -o $$ -o $PPID -x slreportd`
        fi
	exit 0
	;;
*)
	echo $"Usage: $0 {start|stop|restart|reload|status}"
	exit 1
esac
